# dvc parameters listed under `vars` will not be tracked
#  which is used to list settings that do not affect the
#  training or evaluation of the model, e.g. which logger
#  has been used.
vars:
  - logger: mlflow
  - scratch: $CINECA_SCRATCH
stages:
  check_for_venv_path:
    cmd: machines/check_for_venv_path.sh
  mllam_version:
    cmd: '$MLLAM_VENV_PATH/bin/python -c "from neural_lam import __version__; print(__version__)" > version.mllam.txt'
  get_input_datasets:
    cmd: uv run python src/preprocess.py --output ${scratch}/data/sources/icon/ICON312_v1.0.0.zarr
    deps:
    - src/preprocess.py
    outs:
    - ${scratch}/data/sources/icon/ICON312_v1.0.0.zarr
  create_lsm_dataset:
    cmd: '$MLLAM_VENV_PATH/bin/python src/create_state_dataset.py --input ${scratch}/data/sources/icon/ICON312_v1.0.0.zarr --output ${scratch}/data/sources/icon/ICON312_lsm.zarr; touch data/semaphore.lsm.created'
    outs:
    - data/semaphore.lsm.created
  split_dataset:
    cmd: '$MLLAM_VENV_PATH/bin/python -m neural_lam.split_datastore --source_config_path /dcai/projects/cu_0003/user_space/has/git-repos/mllam/mllam-exps-ShCu3/data/datastore.cropped.yaml --interior_config_path /dcai/projects/cu_0003/user_space/has/git-repos/mllam/mllam-exps-ShCu3/data/datastore.interior.yaml --boundary_config_path /dcai/projects/cu_0003/user_space/has/git-repos/mllam/mllam-exps-ShCu3/data/datastore.boundary.yaml'
    deps:
    - data/datastore.cropped.yaml
    outs:
    - data/datastore.boundary.yaml
    - data/datastore.interior.yaml
  create_graph:
    cmd: export DVC_WORKING_DIR=$(pwd); sbatch -W --chdir ~/logs machines/slurm.graph-creation.sh --config_path data/config.yaml ${graph-defaults}
    deps:
    - data/semaphore.lsm.created
    - data/datastore.boundary.yaml
    - data/datastore.interior.yaml
    outs:
    - data/datastore.boundary.zarr
    - data/datastore.interior.zarr
    - data/graph/
  train:
    cmd:
      - export DVC_WORKING_DIR=$(pwd); sbatch -W ${slurm-defaults} --chdir ~/logs machines/slurm.neural-lam.sh --config_path ./data/config.yaml --logger ${logger} --logger-project ${logger-project} ${baseline-defaults}
    deps:
    - version.mllam.txt
    - data/graph/
    - data/config.yaml
    - data/datastore.interior.yaml
    - data/datastore.boundary.yaml
    outs:
    - saved_models:
        persist: true
  evaluate:
    cmd:
    - LASTCHECKPT=./saved_models/train-silky-airs/; export DVC_WORKING_DIR=$(pwd); sbatch -W ${slurm-eval} --chdir ~/logs machines/slurm.neural-lam.sh --config_path ./data/config.yaml --eval val --load \${LASTCHECKPT}/last.ckpt --logger ${logger} --logger-project ${logger-project} ${baseline-eval}
    deps:
    - version.mllam.txt
    - data/graph/
    - data/config.yaml
    - saved_models
    outs:
    - mlruns
