# dvc parameters listed under `vars` will not be tracked
#  which is used to list settings that do not affect the
#  training or evaluation of the model, e.g. which logger
#  has been used.
vars:
  - logger: mlflow
  - scratch: /home/has/data/ 
  - repo: /home/has/repos/mllam-exps-ShCu/ 
stages:
  check_for_venv_path:
    cmd: machines/check_for_venv_path.sh
  mllam_version:
    cmd: 'uv run --reinstall-package neural-lam --reinstall-package mllam-data-prep python -c "from neural_lam import __version__; print(__version__)" > version.mllam.txt; if grep -qi "dirty" version.mllam.txt; then echo "version.mllam.txt contains dirty" >&2; fi'
    #  get_input_datasets:
    #    cmd: 
    #    deps:
    #    - src/preprocess.py
    #    outs:
    #    - ${scratch}/data/sources/icon/ICON312_v1.0.0.zarr
    #  get_grid_information:
    #    cmd: '$MLLAM_VENV_PATH/bin/python src/attach_grid.py'
    #    outs:
    #    - data/grid.zarr
  create_lsm_dataset:
    cmd: 'uv run python src/create_state_dataset.py --input ${scratch}/sources/icon/ICON312_v1.0.0.zarr --output ${scratch}/sources/icon/ICON312_lsm.zarr; touch data/semaphore.lsm.created'
    deps:
    - src/create_state_dataset.py
    outs:
    - data/semaphore.lsm.created
  create_domain_specific_datastores:
    cmd: uv run python src/create_datastores.py ${mllam-data-prep}
    deps:
    - src/create_datastores.py
    - data/template/datastore.interior.yaml
    - data/template/datastore.boundary.yaml
    - data/template/config.yaml
    params:
    - mllam-data-prep
    outs:
    - data/experiment/config
  create_interior_datastore_zarrs:
    foreach: ${mllam-data-prep.domains}
    do:
      cmd: export DVC_WORKING_DIR=$(pwd); uv run --reinstall-package mllam-data-prep mllam_data_prep data/experiment/config/datastore.interior.${item}.yaml --output data/experiment/data/datastore.interior.${item}.zarr
      deps:
      - data/semaphore.lsm.created
      - data/experiment/config/datastore.interior.${item}.yaml
      outs:
      - data/experiment/data/datastore.interior.${item}.zarr
  create_boundary_datastore_zarrs:
    foreach: ${mllam-data-prep.domains}
    do:
      cmd: export DVC_WORKING_DIR=$(pwd); uv run --reinstall-package mllam-data-prep mllam_data_prep data/experiment/config/datastore.boundary.${item}.yaml --output data/experiment/data/datastore.boundary.${item}.zarr
      deps:
      - data/semaphore.lsm.created
      - data/experiment/config/datastore.boundary.${item}.yaml
      outs:
      - data/experiment/data/datastore.boundary.${item}.zarr
  create_graph:
    foreach: ${mllam-data-prep.domains}
    do:
      cmd: export DVC_WORKING_DIR=$(pwd); uv run --reinstall-package neural-lam --reinstall-package mllam-data-prep python -m neural_lam.build_triangular_graph --config_path data/experiment/config/config.${item}.yaml ${graph-defaults} --graph_name triangular2D_split${graph-defaults.splits}_${item}_hierarchical --save_dir data/graph/
      params:
      - graph-defaults
      - data/experiment/config/datastore.boundary.${item}.yaml:
        - inputs.icon_merged.path
        - output.domain_cropping.margin_width_degrees
      #- data/experiment/config/datastore.interior.${item}.yaml:  # too large to track performantly
      #  - inputs.icon_merged.path
      #  - inputs.forcing_features.coord_ranges.cell
      outs:
      - data/graph/triangular2D_split${graph-defaults.splits}_${item}_hierarchical
  train:
    cmd:
      - export DVC_WORKING_DIR=$(pwd); bash machines/slurm.neural-lam.sh --config_paths $(python -c "import yaml; d=yaml.safe_load(open('params.yaml'))['mllam-data-prep']['domains']; print(','.join([f'./data/experiment/config/config.{k}.yaml' for k in d]))") --logger ${logger} --logger-project ${logger-project} ${baseline-defaults} --graph_names $(python -c "import yaml; d=yaml.safe_load(open('params.yaml'))['mllam-data-prep']['domains']; print(','.join([f'triangular2D_split{yaml.safe_load(open('params.yaml'))['graph-defaults']['splits']}_{k}_hierarchical' for k in d]))") --graph_dir data/graph
    deps:
    - version.mllam.txt
    - data/graph/
    - data/experiment/
    params:
    - baseline-defaults
    outs:
    - saved_models:
        persist: true
  evaluate:
    cmd:
    - LASTCHECKPT=./saved_models/train-glare-newt/; export DVC_WORKING_DIR=$(pwd); bash machines/slurm.neural-lam.sh --config_path ./data/config.yaml --eval val --load \${LASTCHECKPT}/last.ckpt --logger ${logger} --logger-project ${logger-project} ${baseline-eval}
    deps:
    - saved_models
    outs:
    - mlruns
