[project]
name = "mllam-exps-shcu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "certifi>2025",
    "distributed>=2025.3.0",
    "dvc>=3.59.1",
    "intake<2",
    "neural-lam",
    "mllam-data-prep",
    "intake-xarray<2.0.0",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "numpy",
    "psutil>=7.0.0",
    "rtree>=1.4.0",
    "scipy==1.15.2",
    "spherely>=0.1.0",
    "nvidia-nccl-cu12>2.26",
    "xarray",
    "zarr<3",
    "ipdb>=0.13.13",
    "xarray-regrid>=0.4.1",
    "xesmf>=0.8.10",
    "uxarray>=0.21.0",
    "spherical-geometry>=1.3.2",
    "trimesh>=4.8.3",
    "dvc-s3>=3.2.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipython>=8.32.0",
]

[tool.uv.sources]
mllam-data-prep = { path = "../mllam-data-prep/" , editable = true}
neural-lam = { path = "../neural-lam-ShCu", editable = true}

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
aiohttp = ">=3.11.16,<4"
xesmf = ">=0.8.10,<0.9"
pyresample = ">=1.34.2,<2"
cdo = ">=2.5.0,<3"
python-cdo = ">=1.6.1,<2"
uxarray = ">=2024"
