[project]
name = "mllam-exps-shcu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "intake>=2.0.8",
    "intake-xarray>=2.0.0",
    "loguru>=0.7.3",
    "mllam-data-prep",
    "neural-lam",
    "numpy<2.0",
    "rtree>=1.4.0",
    "scipy==1.15.2",
    "spherely>=0.1.0",
    "xarray<=2025.2.0",
    "zarr<3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipython>=8.32.0",
]

[tool.uv.sources]
mllam-data-prep = { path = "/Users/haukeschulz/Documents/GitHub/mllam-data-prep" , editable = true}
neural-lam = { path = "../neural-lam", editable = true}
weather-model-graphs = { path = "/Users/haukeschulz/Documents/GitProjects/weather-model-graphs" , editable = true}
