[project]
name = "analysis"
version = "0.1.0"
requires-python = "==3.13"
dependencies = [
    "bokeh>=3.8.2",
    "dask>=2026.1.2",
    "distributed>=2026.1.2",
    "fsspec>=2026.2.0",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "nbformat>=5.10.4",
    "netcdf4>=1.7.4",
    "networkx>=3.6.1",
    "numpy>=2.4.2",
    "plotly>=6.5.2",
    "scores>=2.5.0",
    "seaborn>=0.13.2",
    "shapely>=2.1.2",
    "tqdm>=4.67.3",
    "xarray>=2026.1.0",
    "zarr>=3.1.5",
]
